package com.bytelegend.app.servershared.dal

import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey

@DynamoDbBean
class ReplicatedEvent : Replicable {
    @get: AutoGeneratedReplicableAttribute
    override var lastUpdatedIn: String? = null
    override var lastUpdatedMs: Long? = null

    @get:DynamoDbPartitionKey
    var id: String? = null
    var address: String? = null
    var body: String? = null
}
