package com.bytelegend.app.servershared.dal

import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey

@DynamoDbBean
class ReplicatedEvent : Replicable {
    @get: AutoGeneratedReplicableAttribute
    override var lastUpdatedIn: String = ""
    override var lastUpdatedMs: Long = 0

    @get:DynamoDbPartitionKey
    var id: String = ""
    var address: String = ""
    var body: String = ""
}
