default: true

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 8120

# MD033/no-inline-html - Inline HTML
MD033:
  # Allowed elements
  allowed_elements:
    - details
    - summary
