package com.bytelegend.app.client.api.dsl

import com.bytelegend.app.client.api.GameRuntime
import com.bytelegend.app.shared.GridCoordinate
import com.bytelegend.app.shared.PixelCoordinate
import com.bytelegend.app.shared.objects.GameObject


class MapEntranceBuilder {
    /**
     * Mandatory. The destination map id. When player touches this entrance,
     * the corresponding map will be loaded.
     */
    var destMapId: String? = null

    /**
     * Optional. The id of the entrance to be created. If null,
     * a value will be generated by convention.
     */
    var id: String? = null

    /**
     * Optional. The entrance point id on current map, which can be used to
     * fetch a {@link GamePoint} object. If null, a default id
     * will be generated by convention.
     */
    var coordinatePointId: String? = null

    /**
     * Optional. The map entrance point id on the destination map, which
     * can be used to fetch a GamePoint from destination map.
     */
    var backEntrancePointId: String? = null
}

class NpcBuilder {
    var id: String? = null
    var animationSetIndex: Int? = null
    var onInit: (() -> Unit)? = null
    var onTouch: ((GameObject) -> Unit)? = null
    var onClick: (() -> Unit)? = null
}

class ObjectBuilder {
    var id: String? = null
    var coordinatePointId:String? = null
    var onInit: () -> Unit = {}
    var onTouch: (GameObject) -> Unit = {}
    var onClick: () -> Unit = {}
}

interface GameSceneBuilder {
    fun mapEntrance(builder: MapEntranceBuilder.() -> Unit)
    fun obj(builder: ObjectBuilder.() -> Unit)
    fun npc(builder: NpcBuilder.() -> Unit)
}