name: deploy-webeditor
on:
  workflow_dispatch:
    inputs:
      deployCommit:
        description: 'Commit (empty to deploy the latest commit on release)'
        required: true
        default: 'latest'
      fromBranch:
        description: "From which branch (valid only when commit='latest')"
        required: true
        default: 'release'
jobs:
  deploy:
    name: Deploy webeditor
    runs-on: ubuntu-latest
    if: github.repository == 'ByteLegend/ByteLegend'
    steps:
      - id: determine-webeditor-commit
        name: Determine webeditor commit to deploy
        uses: actions/github-script@v5
        with:
          script: |
            if ('${{ github.event.inputs.deployCommit }}' == 'latest') {
              const response = await github.rest.git.getRef({
                owner: 'ByteLegend',
                repo: 'ByteLegend',
                ref: 'heads/${{ github.event.inputs.fromBranch }}'
              })
              console.log(`Commit to deploy: ${response.data.object.sha}`)
              core.setOutput('deploy-commit', response.data.object.sha)
            } else {
              console.log(`Commit to deploy: ${{ github.event.inputs.deployCommit }}`)
              core.setOutput('deploy-commit', '${{ github.event.inputs.deployCommit }}')
            }
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-test-webeditor.yml
          name: webeditor
          commit: ${{ steps.determine-webeditor-commit.outputs.deploy-commit }}
          path: github1s/dist
          workflow_conclusion: completed
      - run: tree github1s/dist
      - name: Upload /static to s3 Seoul
        run: >
          docker run -v $GITHUB_WORKSPACE/github1s/dist:/dist
          -e AWS_ACCESS_KEY_ID=${{secrets.ACCESS_KEY_ID_SEOUL}}
          -e AWS_SECRET_ACCESS_KEY=${{secrets.SECRET_ACCESS_KEY_SEOUL}}
          -e AWS_DEFAULT_REGION=ap-northeast-2
          amazon/aws-cli
          s3 sync /dist/static s3://bytelegend-web-editor/static
      - name: Upload /static to s3 Beijing
        run: >
          docker run -v $GITHUB_WORKSPACE/github1s/dist:/dist
          -e AWS_ACCESS_KEY_ID=${{secrets.ACCESS_KEY_ID_BEIJING}}
          -e AWS_SECRET_ACCESS_KEY=${{secrets.SECRET_ACCESS_KEY_BEIJING}}
          -e AWS_DEFAULT_REGION=cn-north-1
          amazon/aws-cli
          s3 sync /dist/static s3://bytelegend-web-editor/static
      - name: Sync index.html to s3 Seoul
        run: >
          docker run -v $GITHUB_WORKSPACE/github1s/dist:/dist
          -e AWS_ACCESS_KEY_ID=${{secrets.ACCESS_KEY_ID_SEOUL}}
          -e AWS_SECRET_ACCESS_KEY=${{secrets.SECRET_ACCESS_KEY_SEOUL}}
          -e AWS_DEFAULT_REGION=ap-northeast-2
          amazon/aws-cli
          s3 sync --exclude 'static/*' --delete /dist s3://bytelegend-web-editor
      - name: Sync /index.html to s3 Beijing
        run: >
          docker run -v $GITHUB_WORKSPACE/github1s/dist:/dist
          -e AWS_ACCESS_KEY_ID=${{secrets.ACCESS_KEY_ID_BEIJING}}
          -e AWS_SECRET_ACCESS_KEY=${{secrets.SECRET_ACCESS_KEY_BEIJING}}
          -e AWS_DEFAULT_REGION=cn-north-1
          amazon/aws-cli
          s3 sync --exclude 'static/*' --delete /dist s3://bytelegend-web-editor
