name: release

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'ByteLegend/ByteLegend'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.BYTELEGENDBOT_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: "Release to ECR and S3"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: release -PupdateVersions -DagreePublicBuildScanTermOfService=yes
        env:
          ACCESS_KEY_ID_BEIJING: ${{ secrets.ACCESS_KEY_ID_BEIJING }}
          SECRET_ACCESS_KEY_BEIJING: ${{ secrets.SECRET_ACCESS_KEY_BEIJING }}
          ACCESS_KEY_ID_SEOUL: ${{ secrets.ACCESS_KEY_ID_SEOUL }}
          SECRET_ACCESS_KEY_SEOUL: ${{ secrets.SECRET_ACCESS_KEY_SEOUL }}
          GITHUB_TOKEN: ${{ secrets.BYTELEGENDBOT_TOKEN }}
